editor_imgeditor_index:
    path:  /
    defaults: { _controller: EditorImgeditorBundle:Default:index}
    
editor_imgeditor_action:
    path: /action/{id_action}
    defaults: { _controller: EditorImgeditorBundle:Default:index }
    
editor_imgeditor_fetch_action:
    path: /fetch/{id_action}
    defaults: { _controller: EditorImgeditorBundle:Default:fetch, id_action: ""  }
    
editor_imgeditor_project:
    path: /create/
    defaults: { _controller: EditorImgeditorBundle:Default:create}   

    
editor_imgeditor_rotate:
    path: /rotate/{id_action}
    defaults: { _controller: EditorImgeditorBundle:Default:rotate }
    
editor_imgeditor_crop:
    path: /crop/{id_action}
    defaults: { _controller: EditorImgeditorBundle:Default:crop }
    
editor_imgeditor_undo:
    path: /undo/{hash_kroku}
    defaults: { _controller: EditorImgeditorBundle:Default:undo }
    
editor_imgeditor_redo:
    path: /redo/{hash_kroku}
    defaults: { _controller: EditorImgeditorBundle:Default:redo }
